#include <stdint.h>
#include "thread.h"

extern void native_mmu_reclaim_process_pages(uint64_t pid);
extern void native_ipc_revoke_process_capabilities(uint64_t pid);
extern void print_kernel_log(const char* msg, uint64_t pid);

/**
 * Core kernel-level function responsible for completely destroying a running process
 */
void kernel_terminate_process_context(uint64_t target_pid) {
    // 1. Force fully pull all address descriptors away from the MMU page maps
    native_mmu_reclaim_process_pages(target_pid);
    
    // 2. Revoke and completely purge any outstanding IPC handle routes generated by nt_env.bin
    native_ipc_revoke_process_capabilities(target_pid);
    
    // 3. Complete standard native scheduler state table removals
    print_kernel_log("[*] Clean-room sandbox context fully destroyed for PID: ", target_pid);
}
