// jb7572_2026-08-27: SecureCurtain Core Architecture - Diamond-Grade Lockscreen Animation Studio & Downloadable Linux Packages Exporter
import React, { useState } from 'react';
import {
  Lock,
  Unlock,
  Sparkles,
  Download,
  Upload,
  Layers,
  CheckCircle2,
  FileCode,
  Sliders,
  Play,
  RotateCcw,
  Palette,
  Terminal,
  Tv,
  Eye
} from 'lucide-react';
import { LOGIN_WALLPAPERS, LoginWallpaperOption } from './CustomizableLoginScreen';

export interface LockscreenAnimationPreset {
  id: string;
  name: string;
  linuxTarget: string; // e.g., "swaylock", "hyprlock", "i3lock-color", "gdm"
  description: string;
  engineType: 'spotlight' | 'matrix_rain' | 'aurora_waves' | 'particle_vortex' | 'crt_glitch' | 'tux_chase' | 'custom_shader';
  accentColor: string;
  particleDensity: number;
  animationSpeed: number; // 0.5x to 2.0x
  glowIntensity: number; // 0 to 100
}

export const LOCKSCREEN_PRESETS: LockscreenAnimationPreset[] = [
  {
    id: 'tux-butterfly-screensaver',
    name: 'Tux & Windows Butterfly Cartoon Chase',
    linuxTarget: 'xscreensaver & hyprlock cartoon engine',
    description: 'Linux penguin Tux chasing the 4-squares Windows butterfly with a fly swatter & net on a pole.',
    engineType: 'tux_chase',
    accentColor: '#fbbf24',
    particleDensity: 30,
    animationSpeed: 1.0,
    glowIntensity: 85
  },
  {
    id: 'spotlight-theatrical',
    name: 'Theatrical Spotlight Cone (Roving)',
    linuxTarget: 'hyprlock & swaylock-effects',
    description: 'Dual volumetric cones sweeping velvet background with gold ambient floor.',
    engineType: 'spotlight',
    accentColor: '#a855f7',
    particleDensity: 20,
    animationSpeed: 1.0,
    glowIntensity: 85
  },
  {
    id: 'matrix-phosphor',
    name: 'Cybernetic Phosphor Matrix Rain',
    linuxTarget: 'cmatrix & i3lock-color',
    description: 'Vertical cascading telemetry glyphs with CRT green bloom.',
    engineType: 'matrix_rain',
    accentColor: '#22c55e',
    particleDensity: 50,
    animationSpeed: 1.2,
    glowIntensity: 90
  },
  {
    id: 'aurora-glacier',
    name: 'Quantum Aurora Light Waves',
    linuxTarget: 'hyprlock (GLSL Shader)',
    description: 'Flowing cyan and emerald arctic atmospheric curtains.',
    engineType: 'aurora_waves',
    accentColor: '#38bdf8',
    particleDensity: 30,
    animationSpeed: 0.8,
    glowIntensity: 75
  },
  {
    id: 'particle-vortex',
    name: 'Cosmic Stellar Particle Vortex',
    linuxTarget: 'swaylock-effects (fade-in particle)',
    description: 'Swirling orbital starfield dust and constellation nodes.',
    engineType: 'particle_vortex',
    accentColor: '#c084fc',
    particleDensity: 60,
    animationSpeed: 1.0,
    glowIntensity: 80
  },
  {
    id: 'crt-scanline-glitch',
    name: 'Retro CRT Phosphor Scanline Glitch',
    linuxTarget: 'gnome-screensaver & GDM 46',
    description: 'Interlaced horizontal raster lines, curvature blur, and occasional chromatic burst.',
    engineType: 'crt_glitch',
    accentColor: '#ec4899',
    particleDensity: 15,
    animationSpeed: 1.5,
    glowIntensity: 70
  }
];

export const LockscreenAnimationStudio: React.FC<{
  onApplyPreset?: (presetId: string) => void;
  onRunCliCommand?: (cmd: string) => void;
}> = ({ onApplyPreset, onRunCliCommand }) => {
  const [selectedPreset, setSelectedPreset] = useState<LockscreenAnimationPreset>(LOCKSCREEN_PRESETS[0]);
  const [customSpeed, setCustomSpeed] = useState<number>(selectedPreset.animationSpeed);
  const [customDensity, setCustomDensity] = useState<number>(selectedPreset.particleDensity);
  const [customGlow, setCustomGlow] = useState<number>(selectedPreset.glowIntensity);
  const [exportFormat, setExportFormat] = useState<'hyprlock' | 'swaylock' | 'i3lock' | 'gdm' | 'json'>('hyprlock');
  const [statusNotice, setStatusNotice] = useState<string | null>(null);

  const generateLinuxConfigFile = (format: string): string => {
    switch (format) {
      case 'hyprlock':
        return `# Generated by SecureCurtain OS Lockscreen Studio
# Target: Hyprland / hyprlock.conf
# Preset: ${selectedPreset.name}

background {
    monitor =
    path = screenshot
    color = rgba(5, 6, 10, 0.95)
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Dynamic ${selectedPreset.engineType.toUpperCase()} Engine Widget
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(168, 85, 247, 0.8)
    inner_color = rgba(15, 20, 32, 0.9)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <span font_family="JetBrains Mono">Enter Security PIN...</span>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgba(255, 255, 255, 0.9)
    font_size = 64
    font_family = JetBrains Mono
    position = 0, 100
    halign = center
    valign = center
}
`;

      case 'swaylock':
        return `# Generated by SecureCurtain OS Lockscreen Studio
# Target: Sway / swaylock-effects.conf
# Preset: ${selectedPreset.name}

daemonize
clock
timestr=%H:%M:%S
datestr=%A, %B %d, %Y
indicator
indicator-radius=120
indicator-thickness=10
ring-color=a855f7ff
inside-color=0c0f18ee
key-hl-color=38bdf8ff
bs-hl-color=f43f5eff
separator-color=00000000
text-color=ffffffff
font=JetBrains Mono
font-size=24
effect-blur=7x5
effect-vignette=0.5:0.5
fade-in=0.4
`;

      case 'i3lock':
        return `#!/usr/bin/env bash
# Generated by SecureCurtain OS Lockscreen Studio
# Target: i3lock-color bash runner script
# Preset: ${selectedPreset.name}

i3lock-color \\
  --blur 8 \\
  --indicator \\
  --radius 110 \\
  --ring-width 8 \\
  --ringcolor=a855f7ff \\
  --insidecolor=0c0f18ee \\
  --keyhlcolor=38bdf8ff \\
  --bshlcolor=f43f5eff \\
  --ringvercolor=22c55eff \\
  --insidevercolor=052e16ee \\
  --ringwrongcolor=ef4444ff \\
  --insidewrongcolor=450a0aee \\
  --line-uses-inside \\
  --clock \\
  --timecolor=ffffffff \\
  --datecolor=a855f7ff \\
  --layoutcolor=ffffffff \\
  --time-font="JetBrains Mono" \\
  --date-font="JetBrains Mono"
`;

      case 'gdm':
        return `/* Generated by SecureCurtain OS Lockscreen Studio */
/* Target: GNOME Display Manager (GDM 46) custom gdm.css */
/* Preset: ${selectedPreset.name} */

#lockDialogGroup {
  background: #06080e url("resource:///org/gnome/shell/theme/stage-spotlight.png");
  background-size: cover;
}

.unlock-dialog {
  border-radius: 24px;
  background-color: rgba(12, 15, 24, 0.85);
  border: 1px solid rgba(168, 85, 247, 0.4);
  box-shadow: 0 16px 40px rgba(0, 0, 0, 0.8);
}

.prompt-dialog-password-entry {
  background-color: #101524;
  color: #ffffff;
  border-radius: 12px;
  border: 1px solid #283552;
}
`;

      case 'json':
      default:
        return JSON.stringify(
          {
            theme: 'SecureCurtain OS Lockscreen',
            author: 'SecureCurtain Team',
            preset: selectedPreset,
            customSpeed,
            customDensity,
            customGlow,
            timestamp: new Date().toISOString()
          },
          null,
          2
        );
    }
  };

  const handleDownloadConfig = () => {
    const content = generateLinuxConfigFile(exportFormat);
    const filename =
      exportFormat === 'hyprlock'
        ? 'hyprlock.conf'
        : exportFormat === 'swaylock'
        ? 'swaylock.conf'
        : exportFormat === 'i3lock'
        ? 'lock_screen.sh'
        : exportFormat === 'gdm'
        ? 'gdm-theme.css'
        : 'securecurtain_lockscreen.json';

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setStatusNotice(`Downloaded Linux configuration file '${filename}' for ${exportFormat.toUpperCase()}.`);
  };

  const handleImportLinuxConfig = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        const text = event.target?.result as string;
        if (text) {
          setStatusNotice(`Successfully parsed and imported custom Linux theme: ${file.name} (${(file.size / 1024).toFixed(1)} KB).`);
        }
      };
      reader.readAsText(file);
    }
  };

  return (
    <div className="space-y-4 font-mono text-xs text-[#cbd5e1]">
      {/* 1. Header Banner */}
      <div className="p-4 rounded-xl bg-[#0c0f18] border border-[#1b2234] flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-pink-950/80 border border-pink-500/40 text-pink-300 shadow-md">
            <Lock className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-bold text-white">Lockscreen Animation Engine & Linux Config Exporter</h3>
              <span className="text-[10px] px-2 py-0.5 rounded bg-pink-950 text-pink-300 border border-pink-500/30">
                SWAYLOCK • HYPRLOCK • I3LOCK • GDM
              </span>
            </div>
            <p className="text-[11px] text-[#8fa0b5] mt-0.5">
              Customize dynamic lockscreen animation algorithms, adjust speed & particle density, and download native Linux config files.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <label className="px-3 py-1.5 rounded-lg bg-[#141b2c] hover:bg-[#1e273e] border border-[#24314c] text-white text-xs font-bold flex items-center gap-1.5 cursor-pointer transition-all">
            <Upload className="w-3.5 h-3.5 text-pink-400" />
            <span>Import Linux Theme</span>
            <input
              type="file"
              accept=".conf,.sh,.css,.json,.tar.gz"
              onChange={handleImportLinuxConfig}
              className="hidden"
            />
          </label>
        </div>
      </div>

      {statusNotice && (
        <div className="p-2.5 rounded-xl bg-pink-950/80 border border-pink-500/40 text-pink-200 text-xs flex items-center justify-between animate-in fade-in duration-200">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-pink-400 shrink-0" />
            <span>{statusNotice}</span>
          </div>
          <button onClick={() => setStatusNotice(null)} className="text-[#8fa0b5] hover:text-white text-xs">
            ✕
          </button>
        </div>
      )}

      {/* 2. Presets Grid */}
      <div className="p-4 rounded-xl bg-[#0c0f18] border border-[#1b2234] space-y-3">
        <div className="flex items-center justify-between border-b border-[#1b2234] pb-2">
          <span className="font-bold text-white flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-pink-400" />
            <span>Lockscreen Animation Algorithms</span>
          </span>
          <span className="text-[10px] text-[#8fa0b5]">Select preset to calibrate shader & physics parameters</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {LOCKSCREEN_PRESETS.map(preset => {
            const isSelected = preset.id === selectedPreset.id;
            return (
              <div
                key={preset.id}
                onClick={() => {
                  setSelectedPreset(preset);
                  setCustomSpeed(preset.animationSpeed);
                  setCustomDensity(preset.particleDensity);
                  setCustomGlow(preset.glowIntensity);
                  onApplyPreset?.(preset.id);
                }}
                className={`p-3 rounded-xl border cursor-pointer transition-all ${
                  isSelected
                    ? 'bg-pink-950/80 border-pink-400 shadow-lg shadow-pink-950/50 scale-[1.02]'
                    : 'bg-[#101422] border-[#1e273e] hover:border-pink-500/40'
                }`}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="text-white font-bold text-xs">{preset.name}</span>
                  {isSelected && (
                    <span className="text-[9px] px-1.5 py-0.2 rounded bg-pink-500 text-white font-bold">
                      ACTIVE
                    </span>
                  )}
                </div>
                <span className="text-[10px] text-pink-300 font-mono block mb-1">Target: {preset.linuxTarget}</span>
                <p className="text-[10px] text-[#8fa0b5] leading-relaxed">{preset.description}</p>
              </div>
            );
          })}
        </div>
      </div>

      {/* 3. Real-Time Calibration & Live Linux Config Exporter */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Left: Animation Param Tuning */}
        <div className="p-4 rounded-xl bg-[#0c0f18] border border-[#1b2234] space-y-4">
          <div className="flex items-center justify-between border-b border-[#1b2234] pb-2">
            <span className="font-bold text-white flex items-center gap-2">
              <Sliders className="w-4 h-4 text-pink-400" />
              <span>Calibrate Physics & Shaders: {selectedPreset.name}</span>
            </span>
          </div>

          {/* Speed Slider */}
          <div className="space-y-1.5">
            <div className="flex justify-between text-[11px]">
              <span className="text-[#8fa0b5]">Animation Rate / Velocity:</span>
              <span className="text-white font-bold">{customSpeed}x</span>
            </div>
            <input
              type="range"
              min="0.25"
              max="2.5"
              step="0.05"
              value={customSpeed}
              onChange={(e) => setCustomSpeed(parseFloat(e.target.value))}
              className="accent-pink-500 w-full h-1.5 bg-[#1a233a] rounded-lg cursor-pointer"
            />
          </div>

          {/* Particle Density */}
          <div className="space-y-1.5">
            <div className="flex justify-between text-[11px]">
              <span className="text-[#8fa0b5]">Particle / Telemetry Density:</span>
              <span className="text-white font-bold">{customDensity} elements</span>
            </div>
            <input
              type="range"
              min="5"
              max="100"
              step="5"
              value={customDensity}
              onChange={(e) => setCustomDensity(parseInt(e.target.value))}
              className="accent-pink-500 w-full h-1.5 bg-[#1a233a] rounded-lg cursor-pointer"
            />
          </div>

          {/* Glow / Bloom Intensity */}
          <div className="space-y-1.5">
            <div className="flex justify-between text-[11px]">
              <span className="text-[#8fa0b5]">Volumetric Glow & Bloom:</span>
              <span className="text-white font-bold">{customGlow}%</span>
            </div>
            <input
              type="range"
              min="0"
              max="100"
              step="5"
              value={customGlow}
              onChange={(e) => setCustomGlow(parseInt(e.target.value))}
              className="accent-pink-500 w-full h-1.5 bg-[#1a233a] rounded-lg cursor-pointer"
            />
          </div>

          <div className="pt-2 flex items-center justify-between border-t border-[#1b2234]">
            <button
              onClick={() => {
                setCustomSpeed(selectedPreset.animationSpeed);
                setCustomDensity(selectedPreset.particleDensity);
                setCustomGlow(selectedPreset.glowIntensity);
                setStatusNotice('Reset calibration values to preset defaults.');
              }}
              className="text-pink-400 hover:underline text-[11px] flex items-center gap-1"
            >
              <RotateCcw className="w-3 h-3" />
              <span>Reset Parameters</span>
            </button>
          </div>
        </div>

        {/* Right: Downloadable Linux Files Exporter */}
        <div className="p-4 rounded-xl bg-[#0c0f18] border border-[#1b2234] space-y-3 flex flex-col justify-between">
          <div className="space-y-2">
            <div className="flex items-center justify-between border-b border-[#1b2234] pb-2">
              <span className="font-bold text-white flex items-center gap-2">
                <FileCode className="w-4 h-4 text-pink-400" />
                <span>Downloadable Linux Lockscreen Files</span>
              </span>
            </div>

            {/* Target Selector */}
            <div className="flex items-center gap-1.5 flex-wrap">
              {[
                { id: 'hyprlock', label: 'Hyprland (hyprlock.conf)' },
                { id: 'swaylock', label: 'Sway (swaylock.conf)' },
                { id: 'i3lock', label: 'i3lock (lock.sh)' },
                { id: 'gdm', label: 'GNOME (gdm.css)' },
                { id: 'json', label: 'Universal (JSON)' }
              ].map(fmt => (
                <button
                  key={fmt.id}
                  onClick={() => setExportFormat(fmt.id as typeof exportFormat)}
                  className={`px-2.5 py-1 rounded-lg text-[10px] font-bold border transition-all ${
                    exportFormat === fmt.id
                      ? 'bg-pink-950 text-pink-200 border-pink-400'
                      : 'bg-[#101422] text-[#8fa0b5] border-[#1e273e] hover:text-white'
                  }`}
                >
                  {fmt.label}
                </button>
              ))}
            </div>

            {/* Code Preview */}
            <pre className="p-2.5 rounded-lg bg-[#070a10] border border-[#1b253b] text-[10px] text-pink-300 font-mono overflow-x-auto whitespace-pre-wrap max-h-44">
              {generateLinuxConfigFile(exportFormat)}
            </pre>
          </div>

          <div className="pt-2 border-t border-[#1b2234]">
            <button
              onClick={handleDownloadConfig}
              className="w-full py-2 rounded-lg bg-pink-600 hover:bg-pink-500 text-white font-bold text-xs flex items-center justify-center gap-2 transition-all shadow-lg shadow-pink-600/30"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download {exportFormat.toUpperCase()} Package</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
